// <auto-generated />
using System;
using Ecommerce.MVC.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ecommerce.MVC.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260212155914_MudandoTipo3")]
    partial class MudandoTipo3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.MVC.Entities.Acompanhamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcompanhamentoCategoriaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AcompanhamentoCategoriaId");

                    b.ToTable("Acompanhamentos");
                });

            modelBuilder.Entity("Ecommerce.MVC.Entities.AcompanhamentoCategoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int>("MaxSelecionados")
                        .HasColumnType("integer");

                    b.Property<int>("MinSelecionados")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("boolean");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AcompanhamentoCategorias");
                });

            modelBuilder.Entity("Ecommerce.MVC.Entities.Carrinho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Carrinhos");
                });

            modelBuilder.Entity("Ecommerce.MVC.Entities.CarrinhoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CarrinhoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacao")
                        .HasColumnType("varchar(800)");

                    b.Property<decimal>("PrecoBaseSnapshot")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProdutoNomeSnapshot")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("TempoPreparoMinutosSnapshot")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarrinhoId");

                    b.ToTable("CarrinhoItems");
                });

            modelBuilder.Entity("Ecommerce.MVC.Entities.CarrinhoItemAcompanhamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcompanhamentoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CarrinhoItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("NomeSnapshot")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("PrecoSnapshot")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CarrinhoItemId");

                    b.ToTable("CarrinhoItemAcompanhamentos");
                });

            modelBuilder.Entity("Ecommerce.MVC.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TipoExibicao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Ecommerce.MVC.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("RecebeMarketing")
                        .HasColumnType("boolean");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Ecommerce.MVC.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HorarioRetirada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetodoEntrega")
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<string>("Pagamento")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TaxaEntrega")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Ecommerce.MVC.Entities.PedidoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PrecoAcompanhamentosSnapshot")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrecoBaseSnapshot")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProdutoNomeSnapshot")
                        .HasColumnType("text");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalLinha")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoItens");
                });

            modelBuilder.Entity("Ecommerce.MVC.Entities.PedidoItemAcompanhamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcompanhamentoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("NomeSnapshot")
                        .HasColumnType("text");

                    b.Property<Guid>("PedidoItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PrecoSnapshot")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PedidoItemId");

                    b.ToTable("PedidoItemAcompanhamento");
                });

            modelBuilder.Entity("Ecommerce.MVC.Entities.PedidoSequencial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<int>("UltimoNumero")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PedidoSequenciais");
                });

            modelBuilder.Entity("Ecommerce.MVC.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TempoPreparoMinutos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Ecommerce.MVC.Entities.ProdutoAcompanhamentoCategoria", b =>
                {
                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcompanhamentoCategoriaId")
                        .HasColumnType("uuid");

                    b.HasKey("ProdutoId", "AcompanhamentoCategoriaId");

                    b.HasIndex("AcompanhamentoCategoriaId");

                    b.ToTable("ProdutoAcompanhamentoCategorias");
                });

            modelBuilder.Entity("Ecommerce.MVC.Entities.Acompanhamento", b =>
                {
                    b.HasOne("Ecommerce.MVC.Entities.AcompanhamentoCategoria", "Categoria")
                        .WithMany("Acompanhamentos")
                        .HasForeignKey("AcompanhamentoCategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Ecommerce.MVC.Entities.CarrinhoItem", b =>
                {
                    b.HasOne("Ecommerce.MVC.Entities.Carrinho", "Carrinho")
                        .WithMany("Itens")
                        .HasForeignKey("CarrinhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrinho");
                });

            modelBuilder.Entity("Ecommerce.MVC.Entities.CarrinhoItemAcompanhamento", b =>
                {
                    b.HasOne("Ecommerce.MVC.Entities.CarrinhoItem", "Item")
                        .WithMany("Acompanhamentos")
                        .HasForeignKey("CarrinhoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Ecommerce.MVC.Entities.Pedido", b =>
                {
                    b.HasOne("Ecommerce.MVC.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Ecommerce.MVC.Entities.PedidoItem", b =>
                {
                    b.HasOne("Ecommerce.MVC.Entities.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Ecommerce.MVC.Entities.PedidoItemAcompanhamento", b =>
                {
                    b.HasOne("Ecommerce.MVC.Entities.PedidoItem", "PedidoItem")
                        .WithMany("Acompanhamentos")
                        .HasForeignKey("PedidoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PedidoItem");
                });

            modelBuilder.Entity("Ecommerce.MVC.Entities.Produto", b =>
                {
                    b.HasOne("Ecommerce.MVC.Entities.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Ecommerce.MVC.Entities.ProdutoAcompanhamentoCategoria", b =>
                {
                    b.HasOne("Ecommerce.MVC.Entities.AcompanhamentoCategoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("AcompanhamentoCategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.MVC.Entities.Produto", "Produto")
                        .WithMany("AcompanhamentoCategorias")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Ecommerce.MVC.Entities.AcompanhamentoCategoria", b =>
                {
                    b.Navigation("Acompanhamentos");

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Ecommerce.MVC.Entities.Carrinho", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Ecommerce.MVC.Entities.CarrinhoItem", b =>
                {
                    b.Navigation("Acompanhamentos");
                });

            modelBuilder.Entity("Ecommerce.MVC.Entities.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Ecommerce.MVC.Entities.Pedido", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Ecommerce.MVC.Entities.PedidoItem", b =>
                {
                    b.Navigation("Acompanhamentos");
                });

            modelBuilder.Entity("Ecommerce.MVC.Entities.Produto", b =>
                {
                    b.Navigation("AcompanhamentoCategorias");
                });
#pragma warning restore 612, 618
        }
    }
}
